### ISSUE TITLE
Cyrillic characters in Storage Path 

### ISSUE THREAD

**Issue by MisterDjobsted** [xnotepp/xnote#40] opened 2020-11-06 20:30 UTC
When I specify a path to a folder that contains Cyrillic characters, the application does not understand it.
Older versions did not have this problem.
Example:
https://s.2226.ru/30119_11062207.jpg
https://s.2226.ru/30211_11062254.jpg

i am trying to test 3.0 now
Thanderbird 78.4.0 portable 

Is it possible to fix this?

**Comment by froilo** [comment] 2020-11-08 20:00
@MisterDjobsted: Could you please post a file path (as string, not image) that does not work?

**Comment by MisterDjobsted** [comment] 2020-11-08 20:29
In Explorer, the path to the file is like this:
C:\Users\falko\Google Диск\nspclub.org\Подписи к письмам Thunderbird\xNote
when I select the xNote folder it turns this path into this:
C:\Users\falko\Google 8A:\nspclub.org\>4?8A8 : ?8AL<0< Thunderbird\xNote

**Comment by froilo** [comment] 2020-11-20 17:43
Could reproduce the issue with version 3.0.0. It seems this has been fixed by moving the preferences from the old options dialog to the new one with issue #32.
@MisterDjobsted: If you like, you could try do download the following file, unzip the contained xnote...xpi and install it manually through the add-ons manager to see whether it works for you as well: https://github.com/xnotepp/xnote/suites/1536655597/artifacts/27287494

**Comment by MisterDjobsted** [comment] 2020-11-27 09:02
I installed version 3.1.0a and now the button for specifying the path to the file does not work, I click on it and it does not open the window for selecting a file. 
https://s.2226.ru/21074_11275736.jpg

**Comment by froilo** [comment] 2020-11-27 16:39
Interesting, never saw any issue with the button. Could you please open the error console and see whether there are any errors logged that might be related to XNote? You can open the error console through "Tools - developer tools - error console". Open it, then click on the button and check the latest messages. Usually, errors are marked red on that console.

Just to be sure: You are using Thunderbird 78?

**Comment by MisterDjobsted** [comment] 2020-11-27 20:32
Here's all I see from the errors:
https://s.2226.ru/24204_11272234.jpg
https://s.2226.ru/24652_11272449.jpg

Yes, I'm sure I'm using version 78 - https://s.2226.ru/24864_11272551.jpg

You click on the button and there is no reaction - https://s.2226.ru/25935_GIF-thunder.gif

Thank you for your attention and desire to help!

**Comment by froilo** [comment] 2020-11-29 00:12
Unfortunately, I cannot reproduce the issue and there are no error messages that would give an indication of the problem, For me it takes about a second until that file picker dialog pops up. You might want to retry with the latest development version as it fixes a bug with the note placement contained in your version and a few others, but I am not sure it will change anything with respect to the "Browse" button in the options: https://github.com/xnotepp/xnote/suites/1576581786/artifacts/28483486

If things don't change by that, please try:
1. Deactivate all other add-ons, restart TB and see whether the problem persists. If not, there seems to be some interference.
2. Retry whether the topic is reproducible with a new TB profile without any further add-ons.

**Comment by MisterDjobsted** [comment] 2020-11-29 12:49
Removed all add-ons, rearranged the plugin and still doesn't work.
Installed a new version of TB, installed your plugin and the button still doesn't work.
I apologize, but I did not clarify the important point that I have a portable version of the TB , which is installed on the D: drive.
Perhaps this is the case, perhaps the plugin does not want to work because I have a portable version?

**Comment by froilo** [comment] 2020-11-29 22:04
The TB portable was the important piece of information. Installed it and could reproduce the issue. The problem is that the XNote directory does not exist right after installation. Create an XNote or create the XNote directory within the TB portable profile directory. After that, it should be possible to open the file picker dialog.

**Comment by MisterDjobsted** [comment] 2020-11-29 22:18
It works, thanks a lot!
I also apologize for not immediately clarifying that I have a portable version: ((

**Closed** 2020-12-02 23:12 UTC
Labels: resolved
