### ISSUE TITLE
XNote column resets to minimum width after relaunching Thunderbird

### ISSUE THREAD

**Issue by zevrix** [xnotepp/xnote#50] opened 2020-12-10 05:46 UTC
TB 78.5.1
XNote 3.1.3
macOS 11.0

After relaunching Thunderbird, the XNote column always resets to its minimum size - that is, the width of XNote icon in the column header. It doesn't preserve the column width set by the user while working in TB.
![xnote](https://user-images.githubusercontent.com/51013144/101726733-17d59e80-3a81-11eb-9be2-b00741c9d22a.jpg)

**Comment by moonbeam777** [comment] 2021-01-02 19:27
I have the same issue

**Comment by karltae** [comment] 2021-01-26 07:50
I have it as well.

**Comment by opto** [comment] 2021-02-01 16:56
I can confirm this for 78.7.0 on Win 10.
After TB restart, the column is minimum width. Also, no note text displayed (see extra issue)

**Comment by opto** [comment] 2021-02-01 17:24
or to be more precise: it is unreliable.
E.g.: Inbox: After restart, sometimes, TB forgets that xnote column was selected. Other times, it is displayed.
Sometimes, it is displayed as minimum size (icon only), sometimes, it is displayed wide with text.

Needs some more investigation or debugging. If the column behaviour is unreliable as this, it somewhat points to a TB bug, as we don't do anything about it. This seems to be related to the column picker, unless we have a problem  reading the pref for the width and set the width in a wrong way.
 Klaus

**Comment by zevrix** [comment] 2021-02-12 05:20
So should we submit this bug to Bugzilla too?

**Comment by szelenyit** [comment] 2021-04-28 15:12
Me too:
TB 78.10.0
XNote 3.1.3
Win7 :)
Any development on this?

**Comment by opto** [comment] 2021-04-29 18:51
did you try this release.  https://github.com/xnotepp/xnote/releases/tag/v3.1.4beta.a

A new version will come in the next ca. 10 days,

Klaus

**Comment by szelenyit** [comment] 2021-04-29 19:28
It works, this release solved the column width problem!
Thanks!
Tom

**Comment by zevrix** [comment] 2021-04-30 02:17
Yes, I can also confirm that that this beta solved the column width issue.

Thanks!

**Comment by opto** [comment] 2021-05-09 20:15
closed by new version

**Closed** 2021-05-09 20:15 UTC
Labels: bug
